package com.iot.project.com.iot.project.exception;

public class ConstantsExceptions {
    public static final String RESOURCE_NOT_FOUND = "Resource not found.";
    public static final String INVALID_CREDENTIALS = "Invalid credentials.";
    public static final String INVALID_API_KEY = "Invalid API key.";
    public static final String API_KEY_ALREADY_EXISTS = "API key already exists.";
    public static final String UNAUTHORIZED_ACCESS = "Unauthorized access. You do not have permission to access this resource.";
    public static final String SERVER_ERROR = "An internal server error occurred. Please try again later.";
    public static final String BAD_REQUEST = "Bad request. Please verify your input data.";
    public static final String DATA_NOT_FOUND = "The requested data could not be found.";
    public static final String DUPLICATE_ENTRY = "Duplicate entry detected. The record already exists.";
}
